---
# general vars - everything we might use in context of shelleg
shelleg:
  user: vagrant
  pass: vagrant
  ubuntu:
    box: "bento/ubuntu-16.04"
  centos:
    box: "centos/7"
  net_prefix: "172.16.1"
  subnet: '/24'
  network: '172.16.1.0/24'
  prefix: shelleg
  ram: 512
  ram_infra: 1024
  port: 22
  vagrant_dir: "{{ playbook_dir }}/../vagrant"
  ca_distribution_certs_dir: "{{ playbook_dir }}/../keys_n_certs"
  pki_cert_dir: /etc/pki/tls/certs
  pki_key_dir: /etc/pki/tls/private
  domain_prefix: shelleg
  domain_suffix: local
  domain_name: shelleg.local
  domain: shelleg.local
  dns_searches:
    - shelleg.local
  dns:
    primary: 8.8.8.8
    secondary: 8.8.4.4
